config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :articles
  root 'welcome#index'
  match ':controller(/:action(/:id))', via: [ :get, :post, :patch]

end

app/models/article.rb
class Article < ActiveRecord::Base
	validates :title, presence: { message: "タイトルがない" }
	validates :text, presence: { message: "本文がない" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	
	before_action :set_article, only: [:show, :edit, :update, :destroy]

	def index
		@articles = Article.all
	end

	def new
		@article = Article.new
	end

	def show
	end

	def edit
	end

	def create
		@article = Article.new(article_params)

		if @article.save
			redirect_to @article
		else
			render 'new'
		end
	end

	def update
		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	end

	def destroy
		@article.destroy
		redirect_to articles_path
	end

	def ph1
		@articles = Article.where('title = ?', params[:title])
		render 'articles/index'
	end

	private
		def article_params
			params.require(:article).permit(:title, :text, :videourl)
		end

		def set_article
			@article = Article.find params[:id]
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@aisatu = "あいさつ"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb

<%= form_for @article do |f| %>
	<% if @article.errors.any? %>
		<%= @article.errors.count %>個のエラーがあります<br>
		<% @article.errors.full_messages.each do |msg| %>
			<%= msg %><br>
		<% end %>
	<% end %>

	<p>タイトル</p>
	<%= f.text_field :title %><br>
	<p>動画URL</p>
	<%= f.text_field :videourl %><br>
	<p>本文</p>
	<%= f.text_area :text %><br>
	<%= f.submit %>
<% end %>

app/views/articles/edit.html.erb
<h1>記事の更新</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>動画一覧</h1>
<%#= image_tag "logo.jpg", width: 400 %><br>
<%= link_to "新規動画登録", new_article_path %>

<%= form_tag action: :ph1 do %>
  <div class="field">
    <%= label_tag :title, '動画タイトル：'  %><br />
    <%= text_field_tag :title %>
  </div>
  <%= submit_tag '検索' %>
<% end %>
<%= link_to "動画一覧へ戻る", articles_path %>

<% @articles.each do |article| %>
	<h2 id="title"><%= link_to article.title, article_path(article) %></h2><br>
	<p id="text"><%= article.text %></p><br>
	<%= link_to "編集する", edit_article_path(article) %>
	<%= link_to "削除する", article_path(article), method: :delete, data: { confirm: 'Are you sure' } %>
	<hr>
<% end %>
<br><%= link_to "トップへ戻る", welcome_index_path %>

app/views/articles/keyword.html.erb
<%= form_tag action: :ph1 do %>
  <div class="field">
    <%= label_tag :title, '動画タイトル：'  %><br />
    <%= text_field_tag :title %>
  </div>
  <%= submit_tag '検索' %>
<% end %>
<%= link_to "動画一覧へ戻る", articles_path %>

app/views/articles/new.html.erb
<h1>新規記事作成</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<%== @article.videourl %>
<p><%= @article.text %></p>
<%= link_to "動画一覧へ戻る", articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="wrapper">
	<div id="header">
		<strogn>動画保管</strogn>
	</div id="content">
		<%= yield %>
	<div>
</div>



</body>
</html>

app/views/welcome/index.html.erb
<h1><%= @aisatu %></h1>
<p>Find me in app/views/welcome/index.html.erb</p>
<%= link_to "ブログへ", articles_path %>